repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: check-json
    - id: mixed-line-ending
      args: ['--fix=lf']
      description: Forces to replace line ending by the UNIX 'lf' character.
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.1
    hooks:
    -   id: autopep8
        args:
        - -i
        - --max-line-length=90
        - --ignore=E402
